import type { PublicSighting } from "./sightings.types";

export const mockPublicSightings: PublicSighting[] = [
  {
    id: "sighting-1",
    speciesId: "superb-fairy-wren",
    speciesCommonName: "Superb Fairy-wren",
    speciesScientificName: "Malurus cyaneus",
    conservationStatus: "least_concern",
    rarityTier: "common",
    observedAt: "2026-04-26T07:40:00.000Z",
    latitudePublic: -33.87,
    longitudePublic: 151.2,
    publicLocationLabel: "Approximate location",
    publicAccuracyMeters: 1000,
    locationPrivacyLevel: "public",
    verificationStatus: "community_checked",
    note: "Moving through low shrubs beside the walking track.",
  },
  {
    id: "sighting-2",
    speciesId: "koala",
    speciesCommonName: "Koala",
    speciesScientificName: "Phascolarctos cinereus",
    conservationStatus: "endangered",
    rarityTier: "rare",
    observedAt: "2026-04-25T23:05:00.000Z",
    latitudePublic: -33.8,
    longitudePublic: 151.1,
    publicLocationLabel: "Approximate area",
    publicAccuracyMeters: 10000,
    locationPrivacyLevel: "sensitive",
    verificationStatus: "pending",
    note: "Approximate area only. Sensitive location protected.",
  },
  {
    id: "sighting-3",
    speciesId: "eastern-water-dragon",
    speciesCommonName: "Eastern Water Dragon",
    speciesScientificName: "Intellagama lesueurii",
    conservationStatus: "least_concern",
    rarityTier: "uncommon",
    observedAt: "2026-04-25T02:20:00.000Z",
    latitudePublic: -33.86,
    longitudePublic: 151.22,
    publicLocationLabel: "Approximate location",
    publicAccuracyMeters: 1000,
    locationPrivacyLevel: "public",
    verificationStatus: "verified",
    note: "Basking near a public creek path.",
  },
];
